name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Workflow started"
      - name: Print variable
        run: echo "${{ secrets.NAME }}"